/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceSwing;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author jade
 */
public class Pagina_inicial_view extends javax.swing.JFrame {

    /**
     * Creates new form Pagina_inicial
     */
    
   
    public Pagina_inicial_view() {
        initComponents();
         
        /*
        simples.setToolTipText("Meu tootip");
        Font font = new Font("serif", Font.BOLD | Font.ITALIC, 50);
        simples.setFont(font);
        simples.setForeground(Color.WHITE);
        
        Icon icone = new ImageIcon(getClass().getResource("bag.png"));   
        
        //JLabel imagem = new JLabel(icone, JLabel.RIGHT);
         
               
        jPanel3.add(simples);
        
        jPanel3.add(imagem);
        */
        //this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("bag.png")).getImage());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel3 = new javax.swing.JPanel();
        simples = new javax.swing.JTextField();
        cadastrar_produtos = new javax.swing.JButton();
        cadastrar_vendedor = new javax.swing.JButton();
        cadastrar_cliente1 = new javax.swing.JButton();
        vender = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        simples.setBackground(new java.awt.Color(0, 153, 153));
        simples.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        simples.setText("Bem Vindo(a)!");
        simples.setBorder(null);
        simples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simplesActionPerformed(evt);
            }
        });

        cadastrar_produtos.setText("Cadastrar Produto");
        cadastrar_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_produtosActionPerformed(evt);
            }
        });

        cadastrar_vendedor.setText("Cadastrar Vendedor");
        cadastrar_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_vendedorActionPerformed(evt);
            }
        });

        cadastrar_cliente1.setText("Cadastrar Cliente");
        cadastrar_cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_cliente1ActionPerformed(evt);
            }
        });

        vender.setText("Vender");
        vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrar_vendedor)
                    .addComponent(cadastrar_produtos)
                    .addComponent(simples, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(vender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrar_cliente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(159, 159, 159))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(simples, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(cadastrar_produtos)
                .addGap(18, 18, 18)
                .addComponent(cadastrar_vendedor)
                .addGap(18, 18, 18)
                .addComponent(cadastrar_cliente1)
                .addGap(18, 18, 18)
                .addComponent(vender)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simplesActionPerformed

    private void cadastrar_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_produtosActionPerformed
        // TODO add your handling code here:
        Produto_view pv = new Produto_view();
        
        pv.setVisible(true);
    }//GEN-LAST:event_cadastrar_produtosActionPerformed

    private void cadastrar_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_vendedorActionPerformed
        // TODO add your handling code here:
        
        Vendedor_view vd = new Vendedor_view();
        vd.setVisible(true);
    }//GEN-LAST:event_cadastrar_vendedorActionPerformed

    private void cadastrar_cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_cliente1ActionPerformed
        // TODO add your handling code here
        Cliente_view cv = new Cliente_view();
        cv.setVisible(true);
    }//GEN-LAST:event_cadastrar_cliente1ActionPerformed

    private void venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderActionPerformed
        // TODO add your handling code here:
        Vendas_view vv = new Vendas_view();
        vv.setVisible(true);
    }//GEN-LAST:event_venderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagina_inicial_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagina_inicial_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagina_inicial_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagina_inicial_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagina_inicial_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_cliente1;
    private javax.swing.JButton cadastrar_produtos;
    private javax.swing.JButton cadastrar_vendedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField simples;
    private javax.swing.JButton vender;
    // End of variables declaration//GEN-END:variables
}
