/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceSwing;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Produto;
import model.Venda;
import model.dao.ClienteDao;
import model.dao.ProdutoDao;
import model.dao.VendaDao;

/**
 *
 * @author jade
 */
public class Relatorios_view extends javax.swing.JFrame {

    /**
     * Creates new form Relatorios_view
     */
    public Relatorios_view() {
        initComponents();
       // listarClientesEmDebito();
        verDinheiroEmCaixa();
        //listarProdutosEmFalta();
        verDinheiroParaReceber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valorAPrazo = new javax.swing.JLabel();
        valorAVista = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        relatorio_estoque = new javax.swing.JMenuItem();
        relatorio_clientesEmDebito = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Valor em Caixa:");

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor a Receber:");

        valorAPrazo.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        valorAPrazo.setForeground(new java.awt.Color(255, 255, 255));
        valorAPrazo.setText("0.0");
        valorAPrazo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        valorAVista.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        valorAVista.setForeground(new java.awt.Color(255, 255, 255));
        valorAVista.setText("0.0");
        valorAVista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorAVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorAPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valorAVista))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorAPrazo))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(60, 40));

        jMenu1.setIcon(new javax.swing.ImageIcon("/home/jade/NetBeansProjects/mercadinho_tiuzinho/src/img/opcoes.png")); // NOI18N
        jMenu1.setText("Opções");

        relatorio_estoque.setText("Relatório de estoque");
        relatorio_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorio_estoqueActionPerformed(evt);
            }
        });
        jMenu1.add(relatorio_estoque);

        relatorio_clientesEmDebito.setText("Clientes em Débito");
        relatorio_clientesEmDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorio_clientesEmDebitoActionPerformed(evt);
            }
        });
        jMenu1.add(relatorio_clientesEmDebito);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void relatorio_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorio_estoqueActionPerformed
       Relatorio_produtosEmFalta_view produtosEmFalta = new Relatorio_produtosEmFalta_view();
       produtosEmFalta.setVisible(true);
    }//GEN-LAST:event_relatorio_estoqueActionPerformed

    private void relatorio_clientesEmDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorio_clientesEmDebitoActionPerformed
        Clientes_em_debito clientesEmDebito = new Clientes_em_debito();
        clientesEmDebito.setVisible(true);
    }//GEN-LAST:event_relatorio_clientesEmDebitoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
     public void verDinheiroEmCaixa(){ 
        List<Venda> vendas = new VendaDao().read();
        double valorDaVenda = 0;
        double valorTotal = 0;
        double VariavelAuxiliar = 0;
        
       for(int i = 0; i < vendas.size(); i++){
           String tipoVenda = vendas.get(i).getVenda_aprazo_avista();
           String avista = "À Vista";
         
         
           if((tipoVenda.equals(avista))){
               valorDaVenda = vendas.get(i).getValorTotal_venda();
               valorTotal = VariavelAuxiliar + valorDaVenda;
               
           }
           VariavelAuxiliar = valorTotal;
           valorAVista.setText(Double.toString(VariavelAuxiliar));

       }
       
              
    }
     
    
     
     public void verDinheiroParaReceber(){ 
        List<Venda> vendas = new VendaDao().read();
        double valorDaVenda = 0;
        double valorTotal = 0;
        double VariavelAuxiliar = 0;
        
       for(int i = 0; i < vendas.size(); i++){
           String tipoVenda = vendas.get(i).getVenda_aprazo_avista();
           String avista = "À Prazo";
         
         
           if((tipoVenda.equals(avista))){
               valorDaVenda = vendas.get(i).getValorTotal_venda();
               valorTotal = VariavelAuxiliar + valorDaVenda;
               
           }
           VariavelAuxiliar = valorTotal;
           valorAPrazo.setText(Double.toString(VariavelAuxiliar));

       }
       
              
    }
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorios_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorios_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorios_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorios_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorios_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem relatorio_clientesEmDebito;
    private javax.swing.JMenuItem relatorio_estoque;
    private javax.swing.JLabel valorAPrazo;
    private javax.swing.JLabel valorAVista;
    // End of variables declaration//GEN-END:variables
}
