/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceSwing;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Produto;
import model.Venda;
import model.Venda_produto;
import model.dao.ProdutoDao;
import model.dao.VendaDao;
import model.dao.Venda_produtoDao;

/**
 *
 * @author jade
 */
public class Vendas_view extends javax.swing.JFrame {

    /**
     * Creates new form Vendas_view
     */
    public Vendas_view() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_plano_de_fundo = new javax.swing.JPanel();
        jPanel_Topo_tela = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        data_da_venda = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cod_ultima_venda = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nome_do_produto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_de_compras = new javax.swing.JTable();
        nome_do_produto_venda = new javax.swing.JLabel();
        jPanel_inf_venda = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codigo_produto_venda = new javax.swing.JTextField();
        cpf_cliente_venda = new javax.swing.JFormattedTextField();
        JButton_adicionar_cpf_venda = new javax.swing.JButton();
        quantidade_produto_venda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        preco_produto_venda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        valor_total_itens_venda = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        total_a_pagar_venda = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        valor_recebido_venda = new javax.swing.JTextField();
        troco_venda1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton_adicionar_produto = new javax.swing.JButton();
        verPreco = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 565));

        jPanel_plano_de_fundo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_plano_de_fundo.setPreferredSize(new java.awt.Dimension(880, 565));

        jPanel_Topo_tela.setBackground(new java.awt.Color(0, 153, 153));
        jPanel_Topo_tela.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mercadinho");

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tiuzinho");

        jLabel15.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Data:");

        data_da_venda.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        data_da_venda.setForeground(new java.awt.Color(255, 255, 255));
        data_da_venda.setText("_/_/_");

        jLabel16.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Venda:");

        cod_ultima_venda.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        cod_ultima_venda.setForeground(new java.awt.Color(255, 255, 255));
        cod_ultima_venda.setText("00");

        javax.swing.GroupLayout jPanel_Topo_telaLayout = new javax.swing.GroupLayout(jPanel_Topo_tela);
        jPanel_Topo_tela.setLayout(jPanel_Topo_telaLayout);
        jPanel_Topo_telaLayout.setHorizontalGroup(
            jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Topo_telaLayout.createSequentialGroup()
                .addGroup(jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Topo_telaLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Topo_telaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Topo_telaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data_da_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(jPanel_Topo_telaLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cod_ultima_venda)
                        .addContainerGap(401, Short.MAX_VALUE))))
        );
        jPanel_Topo_telaLayout.setVerticalGroup(
            jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Topo_telaLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Topo_telaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(data_da_venda)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Topo_telaLayout.createSequentialGroup()
                        .addGroup(jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cod_ultima_venda))
                        .addGap(43, 43, 43))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nome_do_produto.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        nome_do_produto.setForeground(new java.awt.Color(255, 255, 255));
        nome_do_produto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome_do_produto.setText("Cupom do Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nome_do_produto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nome_do_produto)
        );

        lista_de_compras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        lista_de_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cód. Prod.", "Qtd.", "Valor", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lista_de_compras);

        nome_do_produto_venda.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        nome_do_produto_venda.setForeground(new java.awt.Color(20, 10, 10));
        nome_do_produto_venda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome_do_produto_venda.setText("Produto");

        jPanel_inf_venda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel5.setText("Quantidade:");

        codigo_produto_venda.setBackground(new java.awt.Color(255, 255, 255));
        codigo_produto_venda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigo_produto_venda.setBorder(null);
        codigo_produto_venda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigo_produto_vendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigo_produto_vendaFocusLost(evt);
            }
        });

        cpf_cliente_venda.setBackground(new java.awt.Color(255, 255, 255));
        cpf_cliente_venda.setBorder(null);
        try {
            cpf_cliente_venda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        JButton_adicionar_cpf_venda.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        JButton_adicionar_cpf_venda.setText("Adicionar CPF");
        JButton_adicionar_cpf_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_adicionar_cpf_vendaActionPerformed(evt);
            }
        });

        quantidade_produto_venda.setBackground(new java.awt.Color(255, 255, 255));
        quantidade_produto_venda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantidade_produto_venda.setBorder(null);
        quantidade_produto_venda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantidade_produto_vendaFocusGained(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel6.setText("Código:");

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel7.setText("Valor Total:");

        preco_produto_venda.setBackground(new java.awt.Color(255, 255, 255));
        preco_produto_venda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        preco_produto_venda.setBorder(null);
        preco_produto_venda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                preco_produto_vendaFocusGained(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel8.setText("Preço Unit.:");

        valor_total_itens_venda.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        valor_total_itens_venda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valor_total_itens_venda.setText("0.0");
        valor_total_itens_venda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        javax.swing.GroupLayout jPanel_inf_vendaLayout = new javax.swing.GroupLayout(jPanel_inf_venda);
        jPanel_inf_venda.setLayout(jPanel_inf_vendaLayout);
        jPanel_inf_vendaLayout.setHorizontalGroup(
            jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                        .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(codigo_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                                .addComponent(quantidade_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preco_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                        .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                                .addComponent(cpf_cliente_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JButton_adicionar_cpf_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inf_vendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(valor_total_itens_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel_inf_vendaLayout.setVerticalGroup(
            jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButton_adicionar_cpf_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf_cliente_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidade_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preco_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valor_total_itens_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel11.setText("Total a pagar:");

        total_a_pagar_venda.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        total_a_pagar_venda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_a_pagar_venda.setText("0.0");
        total_a_pagar_venda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        jLabel13.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel13.setText("Valor Recebido:");

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel9.setText("Troco:");

        valor_recebido_venda.setBackground(new java.awt.Color(255, 255, 255));
        valor_recebido_venda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor_recebido_venda.setText("0.0");
        valor_recebido_venda.setBorder(null);

        troco_venda1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        troco_venda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        troco_venda1.setText("0.0");
        troco_venda1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_a_pagar_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(64, 64, 64))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valor_recebido_venda)
                    .addComponent(troco_venda1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total_a_pagar_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valor_recebido_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(troco_venda1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jButton_adicionar_produto.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton_adicionar_produto.setText("Adicionar Produto");
        jButton_adicionar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_adicionar_produtoActionPerformed(evt);
            }
        });

        verPreco.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        verPreco.setIcon(new javax.swing.ImageIcon("/home/jade/NetBeansProjects/mercadinho_tiuzinho/src/img/pesquisarCli.png")); // NOI18N
        verPreco.setText("Ver Preço");
        verPreco.setBorder(null);

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("/home/jade/NetBeansProjects/mercadinho_tiuzinho/src/img/modificarPreco.png")); // NOI18N
        jButton1.setText("Modificar Preço");
        jButton1.setBorder(null);

        javax.swing.GroupLayout jPanel_plano_de_fundoLayout = new javax.swing.GroupLayout(jPanel_plano_de_fundo);
        jPanel_plano_de_fundo.setLayout(jPanel_plano_de_fundoLayout);
        jPanel_plano_de_fundoLayout.setHorizontalGroup(
            jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Topo_tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nome_do_produto_venda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_plano_de_fundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_adicionar_produto)
                .addGap(313, 313, 313))
            .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jPanel_inf_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                .addComponent(verPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_plano_de_fundoLayout.setVerticalGroup(
            jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                .addComponent(jPanel_Topo_tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(nome_do_produto_venda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                        .addGroup(jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel_inf_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addComponent(jButton_adicionar_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_plano_de_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_plano_de_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_adicionar_cpf_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_adicionar_cpf_vendaActionPerformed
        Venda v = new Venda();
        VendaDao vd = new VendaDao();
        List<Venda> lv = new VendaDao().read();
        int lista;
        
        v.setCpf_cliente(cpf_cliente_venda.getText());

        vd.create(v);
        pegarUltimoCod();
    }//GEN-LAST:event_JButton_adicionar_cpf_vendaActionPerformed

    private void codigo_produto_vendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigo_produto_vendaFocusGained
          
    
    }//GEN-LAST:event_codigo_produto_vendaFocusGained

    private void jButton_adicionar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_adicionar_produtoActionPerformed
        adicionarProdutos();
    }//GEN-LAST:event_jButton_adicionar_produtoActionPerformed

    private void quantidade_produto_vendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantidade_produto_vendaFocusGained
        
    }//GEN-LAST:event_quantidade_produto_vendaFocusGained

    private void preco_produto_vendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_preco_produto_vendaFocusGained
         calculaValorDeItens();
    }//GEN-LAST:event_preco_produto_vendaFocusGained

    private void codigo_produto_vendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigo_produto_vendaFocusLost
        carregaPreco();
    }//GEN-LAST:event_codigo_produto_vendaFocusLost

    public void pegarUltimoCod(){
        Venda v = new Venda();
        List<Venda> vd = new VendaDao().read();
        boolean achou = false;

        if(vd.size() > 0){
            
        String i = Integer.toString(vd.get(vd.size()-1).getCod_venda());
        cod_ultima_venda.setText(i);
        
        }  
          
    }
    
    public void RetornarNomeProduto(){
    
    List<Produto> produtos = new ProdutoDao().read();
    Produto p = new Produto();
    ProdutoDao pd= new ProdutoDao();
    String nome = null;
    String codigoDigitado;
    codigoDigitado = codigo_produto_venda.getText();
    boolean achou = false;
     
    for(int i = 0; i < produtos.size(); i++){
        String codBanco = Integer.toString(produtos.get(i).getCod_produto());
        if(codigoDigitado.equals(codBanco)){
            //nome = produtos.get(i).getNome_produto();
            nome_do_produto.setText(produtos.get(i).getNome_produto());
        }
  
    }
  
        
}
    
    public double calculaValorDeItens(){
    double subValor;
    int quantidade;
    double valorUnitario;
     
    quantidade = Integer.parseInt(quantidade_produto_venda.getText());
    valorUnitario = Double.parseDouble(preco_produto_venda.getText());
    
    subValor = (quantidade * valorUnitario);
     
    valor_total_itens_venda.setText(Double.toString(subValor));
     
    return subValor;
     
}
    
    public void carregaPreco(){
    Produto p = new Produto();
    List<Produto> produtos = new ProdutoDao().read();
    ProdutoDao pd = new ProdutoDao();
     
    int codDigitado = Integer.parseInt(codigo_produto_venda.getText());
    
    for(int i = 0; i < produtos.size(); i++){
         
        if(codDigitado == produtos.get(i).getCod_produto()){
            preco_produto_venda.setText(Double.toString(produtos.get(i).getPreco_produto()));
        }
    }
    
}
    
    public void subtrairquantidade(){
    Produto p = new Produto();
    List<Produto> produtos = new ProdutoDao().read();
    ProdutoDao pd = new ProdutoDao();
     
    int codDigitado = Integer.parseInt(codigo_produto_venda.getText());
    int quantidadeDig = Integer.parseInt(quantidade_produto_venda.getText());
    int quantBd;
    boolean maior = false;
     
    for(int i = 0; i < produtos.size(); i++){
         
        if(codDigitado == produtos.get(i).getCod_produto()){
            quantBd = produtos.get(i).getQuantidade_produto();
            quantBd = quantBd - quantidadeDig;
            produtos.get(i).setQuantidade_produto(quantBd);
            pd.update(produtos.get(i));
            
            if(quantidadeDig > produtos.get(i).getQuantidade_produto()){
                maior = true;
                JOptionPane.showMessageDialog(null, "Quantidade maior que estoque!");
            }
        }
    }
 
}
    
    public void calcularTroco(){
    double valorRecebido = Double.parseDouble(valor_recebido_venda.getText());
    double valorTotalCompra = Double.parseDouble(total_a_pagar_venda.getText());
    double troco ;
        
    troco = (valorRecebido - valorTotalCompra);
        
    valor_total_itens_venda.setText(Double.toString(troco));
        
}
   
   
    public void adicionarProdutos(){
        
    Venda_produto vp = new Venda_produto();
    Venda_produtoDao vpd = new Venda_produtoDao();
    List<Venda_produto> vpl = new Venda_produtoDao().read();
    Venda v = new Venda();
    ArrayList<Venda_produto> list = new ArrayList<>();
    double valorFinal = 0;
    double varAuxiliar = 0;
        
    
        vp.setCod_produtoFk(Integer.parseInt(codigo_produto_venda.getText()));
        vp.setCod_vendaFk(Integer.parseInt(cod_ultima_venda.getText()));
        vp.setQuantidade_produtos(Integer.parseInt(quantidade_produto_venda.getText()));

        subtrairquantidade();

        vp.setValor_unitarioproduto(Double.parseDouble(valor_total_itens_venda.getText()));
        /*
        if(modifica_preco.isSelected()){

        }
        */ 

        vp.setTotal_venda(Double.parseDouble(valor_total_itens_venda.getText())); 
        vpd.create(vp);
        
        vpl.add(vp);
        
        
        
  
    int codV = Integer.parseInt(cod_ultima_venda.getText());
    int codP = Integer.parseInt(codigo_produto_venda.getText());
    
    for(int i =0 ; i < vpl.size(); i++){
        int k = 0;
         
   
            lista_de_compras.setValueAt(vpl.get(i).getCod_produtoFk(), i, k);
            lista_de_compras.setValueAt(vpl.get(i).getQuantidade_produtos(), i, k+1);
            lista_de_compras.setValueAt(vpl.get(i).getValor_unitarioproduto(), i, k+2);
            lista_de_compras.setValueAt(vpl.get(i).getTotal_venda(), i, k+3);
  
        double subtotal = vpl.get(i).getTotal_venda();
        valorFinal = (varAuxiliar + subtotal);
        varAuxiliar = valorFinal;
         k++;
        
                  
    }
        
        total_a_pagar_venda.setText(Double.toString(varAuxiliar)); 
    
    
    limparCampos();
       
}
    
    public void limparCampos(){
        codigo_produto_venda.setText("");
        nome_do_produto.setText("");
        cpf_cliente_venda.setText("");
        quantidade_produto_venda.setText("");
        preco_produto_venda.setText("");
        valor_total_itens_venda.setText("");
        valor_recebido_venda.setText("");
        valor_total_itens_venda.setText("");
        total_a_pagar_venda.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_adicionar_cpf_venda;
    private javax.swing.JLabel cod_ultima_venda;
    private javax.swing.JTextField codigo_produto_venda;
    private javax.swing.JFormattedTextField cpf_cliente_venda;
    private javax.swing.JLabel data_da_venda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_adicionar_produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_Topo_tela;
    private javax.swing.JPanel jPanel_inf_venda;
    private javax.swing.JPanel jPanel_plano_de_fundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lista_de_compras;
    private javax.swing.JLabel nome_do_produto;
    private javax.swing.JLabel nome_do_produto_venda;
    private javax.swing.JTextField preco_produto_venda;
    private javax.swing.JTextField quantidade_produto_venda;
    private javax.swing.JLabel total_a_pagar_venda;
    private javax.swing.JLabel troco_venda1;
    private javax.swing.JTextField valor_recebido_venda;
    private javax.swing.JLabel valor_total_itens_venda;
    private javax.swing.JButton verPreco;
    // End of variables declaration//GEN-END:variables
}
