
package interfaceSwing;

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Login;
import model.Produto;
import model.Venda;
import model.Venda_produto;
import model.Vendedor;
import model.dao.ClienteDao;
import model.dao.LoginDao;
import model.dao.ProdutoDao;
import model.dao.VendaDao;
import model.dao.Venda_produtoDao;
import model.dao.VendedorDao;

/**
 *
 * @author jade
 */
public class Vendas_view extends javax.swing.JFrame {

    /**
     * Creates new form Vendas_view
     */
    public Vendas_view() {
        initComponents();
        titulo.setToolTipText("Jade Development Systems");
      
        mostrarVendedorDaVenda();
        
        java.util.Date dat;
        dat = new java.util.Date();
        SimpleDateFormat formato;
        formato = new SimpleDateFormat("dd-MM-YYYY");
        data_da_venda.setText(formato.format(dat));
        //nome_do_produto_venda.setVisible(false);
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel_plano_de_fundo = new javax.swing.JPanel();
        jPanel_Topo_tela = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        data_da_venda = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        informacao2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_de_compras = new javax.swing.JTable();
        jPanel_inf_venda = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codigo_produto_venda = new javax.swing.JTextField();
        cpf_cliente_venda = new javax.swing.JFormattedTextField();
        JButton_adicionar_cpf_venda = new javax.swing.JButton();
        quantidade_produto_venda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        preco_produto_venda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        aprazo = new javax.swing.JRadioButton();
        avista = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        total_a_pagar_venda = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        valor_recebido_venda = new javax.swing.JTextField();
        troco_venda1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        verPreco = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cod_ultima_venda = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        informacao = new javax.swing.JLabel();
        cancelar_venda = new javax.swing.JButton();
        valor_total_item_venda = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nome_do_produto_venda = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 565));

        jPanel_plano_de_fundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        jPanel_plano_de_fundo.setMaximumSize(new java.awt.Dimension(880, 565));
        jPanel_plano_de_fundo.setMinimumSize(new java.awt.Dimension(880, 565));
        jPanel_plano_de_fundo.setPreferredSize(new java.awt.Dimension(880, 565));

        jPanel_Topo_tela.setBackground(new java.awt.Color(0, 153, 153));
        jPanel_Topo_tela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Data:");

        data_da_venda.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        data_da_venda.setForeground(new java.awt.Color(255, 255, 255));
        data_da_venda.setText("_/_/_");

        titulo.setFont(new java.awt.Font("Century Schoolbook L", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setIcon(new javax.swing.ImageIcon("/home/jade/NetBeansProjects/mercadinho_tiuzinho/src/img/icone_jade.png")); // NOI18N
        titulo.setText("JaDeS");

        informacao2.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        informacao2.setForeground(new java.awt.Color(255, 255, 255));
        informacao2.setText("Informação");

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vendedor:");

        javax.swing.GroupLayout jPanel_Topo_telaLayout = new javax.swing.GroupLayout(jPanel_Topo_tela);
        jPanel_Topo_tela.setLayout(jPanel_Topo_telaLayout);
        jPanel_Topo_telaLayout.setHorizontalGroup(
            jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Topo_telaLayout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Topo_telaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(informacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Topo_telaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(data_da_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );
        jPanel_Topo_telaLayout.setVerticalGroup(
            jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Topo_telaLayout.createSequentialGroup()
                .addGroup(jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(data_da_venda))
                    .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
            .addGroup(jPanel_Topo_telaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel_Topo_telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(informacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lista_de_compras.setAutoCreateRowSorter(true);
        lista_de_compras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        lista_de_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Prod.", "Qtd.", "Valor", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        lista_de_compras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lista_de_comprasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(lista_de_compras);

        jPanel_inf_venda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel5.setText("Quantidade:");

        codigo_produto_venda.setBackground(new java.awt.Color(255, 255, 255));
        codigo_produto_venda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigo_produto_venda.setBorder(null);
        codigo_produto_venda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigo_produto_vendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigo_produto_vendaFocusLost(evt);
            }
        });

        cpf_cliente_venda.setBackground(new java.awt.Color(255, 255, 255));
        cpf_cliente_venda.setBorder(null);
        try {
            cpf_cliente_venda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        JButton_adicionar_cpf_venda.setBackground(new java.awt.Color(0, 122, 122));
        JButton_adicionar_cpf_venda.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        JButton_adicionar_cpf_venda.setIcon(new javax.swing.ImageIcon("/home/jade/NetBeansProjects/mercadinho_tiuzinho/src/img/dicionar cpf.png")); // NOI18N
        JButton_adicionar_cpf_venda.setBorder(null);
        JButton_adicionar_cpf_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_adicionar_cpf_vendaActionPerformed(evt);
            }
        });

        quantidade_produto_venda.setBackground(new java.awt.Color(255, 255, 255));
        quantidade_produto_venda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantidade_produto_venda.setBorder(null);
        quantidade_produto_venda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantidade_produto_vendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantidade_produto_vendaFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel6.setText("Código:");

        preco_produto_venda.setBackground(new java.awt.Color(255, 255, 255));
        preco_produto_venda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        preco_produto_venda.setBorder(null);
        preco_produto_venda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                preco_produto_vendaFocusGained(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel8.setText("Preço Unit.:");

        aprazo.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        aprazo.setForeground(new java.awt.Color(0, 0, 0));
        aprazo.setText("À Prazo");

        avista.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        avista.setForeground(new java.awt.Color(0, 0, 0));
        avista.setSelected(true);
        avista.setText("À Vista");

        javax.swing.GroupLayout jPanel_inf_vendaLayout = new javax.swing.GroupLayout(jPanel_inf_venda);
        jPanel_inf_venda.setLayout(jPanel_inf_vendaLayout);
        jPanel_inf_vendaLayout.setHorizontalGroup(
            jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                        .addComponent(cpf_cliente_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButton_adicionar_cpf_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aprazo)
                            .addComponent(avista, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                        .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigo_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                                .addComponent(quantidade_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(preco_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel_inf_vendaLayout.setVerticalGroup(
            jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButton_adicionar_cpf_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf_cliente_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_inf_vendaLayout.createSequentialGroup()
                        .addComponent(aprazo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avista)))
                .addGap(58, 58, 58)
                .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_inf_vendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidade_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preco_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel11.setText("Total a pagar:");

        total_a_pagar_venda.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        total_a_pagar_venda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_a_pagar_venda.setText("0.0");
        total_a_pagar_venda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        jLabel13.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel13.setText("Valor Recebido:");

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel9.setText("Troco:");

        valor_recebido_venda.setBackground(new java.awt.Color(255, 255, 255));
        valor_recebido_venda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor_recebido_venda.setText("0.0");
        valor_recebido_venda.setBorder(null);
        valor_recebido_venda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valor_recebido_vendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                valor_recebido_vendaFocusLost(evt);
            }
        });

        troco_venda1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        troco_venda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        troco_venda1.setText("0.0");
        troco_venda1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_a_pagar_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(64, 64, 64))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valor_recebido_venda)
                    .addComponent(troco_venda1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total_a_pagar_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valor_recebido_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(troco_venda1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        verPreco.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        verPreco.setIcon(new javax.swing.ImageIcon("/home/jade/NetBeansProjects/mercadinho_tiuzinho/src/img/pesquisarCli.png")); // NOI18N
        verPreco.setText("Ver Preço");
        verPreco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPrecoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Venda:");

        cod_ultima_venda.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        cod_ultima_venda.setForeground(new java.awt.Color(0, 0, 0));
        cod_ultima_venda.setText("00");

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("/home/jade/NetBeansProjects/mercadinho_tiuzinho/src/img/excluir_produto.png")); // NOI18N
        jButton1.setText("Excluir Produto");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        informacao.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        informacao.setForeground(new java.awt.Color(0, 153, 153));
        informacao.setText("Informação");

        cancelar_venda.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        cancelar_venda.setIcon(new javax.swing.ImageIcon("/home/jade/NetBeansProjects/mercadinho_tiuzinho/src/img/errado.png")); // NOI18N
        cancelar_venda.setText("Cancelar Venda");
        cancelar_venda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelar_venda.setPreferredSize(new java.awt.Dimension(148, 36));
        cancelar_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_vendaActionPerformed(evt);
            }
        });

        valor_total_item_venda.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        valor_total_item_venda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valor_total_item_venda.setText("0.0");
        valor_total_item_venda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel7.setText("Valor Total:");

        nome_do_produto_venda.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        nome_do_produto_venda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome_do_produto_venda.setText("Produto");

        javax.swing.GroupLayout jPanel_plano_de_fundoLayout = new javax.swing.GroupLayout(jPanel_plano_de_fundo);
        jPanel_plano_de_fundo.setLayout(jPanel_plano_de_fundoLayout);
        jPanel_plano_de_fundoLayout.setHorizontalGroup(
            jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Topo_tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nome_do_produto_venda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                .addGroup(jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_inf_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                        .addGroup(jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                                .addComponent(verPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelar_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cod_ultima_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(informacao, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(valor_total_item_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_plano_de_fundoLayout.setVerticalGroup(
            jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                .addComponent(jPanel_Topo_tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cod_ultima_venda)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar_venda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(nome_do_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                        .addGroup(jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_inf_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_plano_de_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valor_total_item_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE))
                            .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(informacao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_plano_de_fundoLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_plano_de_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_plano_de_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_adicionar_cpf_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_adicionar_cpf_vendaActionPerformed
        informacao.setText("CPF adicionado!");
        Venda venda = new Venda();
        VendaDao vendaDao = new VendaDao();
                        
        venda.setCpf_cliente(cpf_cliente_venda.getText());
         if(aprazo.isSelected()){
            venda.setVenda_aprazo_avista(aprazo.getText());
        }
        if(avista.isSelected()){
            venda.setVenda_aprazo_avista(avista.getText());
        }
        //venda.setValorTotal_venda(Double.parseDouble(total_a_pagar_venda.getText()));
        java.util.Date dat;
        dat = new java.util.Date();
        SimpleDateFormat formato;
        formato = new SimpleDateFormat("dd-MM-YYYY");
        //data_da_venda.setText(formato.format(dat));
        //java.sql.Date data = null;
        try {
            dat = new java.sql.Date(formato.parse(data_da_venda.getText()).getTime());
        } catch (ParseException ex) {
            Logger.getLogger(Vendas_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        venda.setData_venda((Date) dat);
        vendaDao.create(venda);
        mostrarCodigoDaVenda();
        troco_venda1.setText("0.0");
    }//GEN-LAST:event_JButton_adicionar_cpf_vendaActionPerformed

    private void codigo_produto_vendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigo_produto_vendaFocusGained
          informacao.setText("Digite o código do produto!");
    
    }//GEN-LAST:event_codigo_produto_vendaFocusGained

    private void quantidade_produto_vendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantidade_produto_vendaFocusGained
        informacao.setText("Digite a quantidade!");
        carregarNomeDoProdutoVendido();
    }//GEN-LAST:event_quantidade_produto_vendaFocusGained

    private void preco_produto_vendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_preco_produto_vendaFocusGained
        //calcularTotalAPagar();
        adicionarProdutosNaCompra();
        
        adicionarProdutosCompradosNaTabela();
        
            totalAPgar();
            FinalizarCompra();
            limparCampos();
            
    }//GEN-LAST:event_preco_produto_vendaFocusGained

    public void totalAPgar(){
        double valorCompra = Double.parseDouble(total_a_pagar_venda.getText());
        double valorAuxiliar = 0;
        
        double valorItem = Double.parseDouble(valor_total_item_venda.getText());
            valorAuxiliar = (valorCompra + valorItem);
            
            
            total_a_pagar_venda.setText(Double.toString(valorAuxiliar));
    }
    
    private void codigo_produto_vendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigo_produto_vendaFocusLost
        carregarPreco();
        //carregarNomeDoProdutoVendido();
        
    }//GEN-LAST:event_codigo_produto_vendaFocusLost

    private void quantidade_produto_vendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantidade_produto_vendaFocusLost
        
        atualizarQuantidadeNoBanco();
        calcularValorTotalDeUmItem();
        //calcularTotalDaCompra();
    }//GEN-LAST:event_quantidade_produto_vendaFocusLost

    private void verPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPrecoActionPerformed
        Mostrar_produto mp = new Mostrar_produto();
        mp.setVisible(true);
    }//GEN-LAST:event_verPrecoActionPerformed

    private void valor_recebido_vendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valor_recebido_vendaFocusLost
        informacao.setText("Compra Finalizada!");
        calcularTroco();
        cod_ultima_venda.setText("00");
        total_a_pagar_venda.setText("0.0");
        
        valor_total_item_venda.setText("0.0");
        valor_recebido_venda.setText("0.0");
        nome_do_produto_venda.setText("Produto");
        
        limparTabela();
        
    }//GEN-LAST:event_valor_recebido_vendaFocusLost
    
    public void limparTabela(){
   
           while (lista_de_compras.getModel().getRowCount() > 0) {  
           ((DefaultTableModel) lista_de_compras.getModel()).removeRow(0);  
       } 
    }
    
    private void valor_recebido_vendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valor_recebido_vendaFocusGained
        informacao.setText("Finalizando compra!");
        
    }//GEN-LAST:event_valor_recebido_vendaFocusGained

    private void lista_de_comprasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lista_de_comprasKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_de_comprasKeyReleased

    private void cancelar_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_vendaActionPerformed
       excluirVenda_produto();
        excluirVenda();
        
    }//GEN-LAST:event_cancelar_vendaActionPerformed

    public void FinalizarCompra(){
        List<Venda> listaVenda = new VendaDao().read();
       VendaDao vendas = new VendaDao();
        Venda venda = new Venda();
        String codigoDigitado = cod_ultima_venda.getText();
        
        for(int i = 0; i < listaVenda.size(); i++){
            String codigoVendaBd = Integer.toString(listaVenda.get(i).getCod_venda());
            if(codigoDigitado.equals(codigoVendaBd)){
                listaVenda.get(i).setValorTotal_venda(Double.parseDouble(total_a_pagar_venda.getText()));
                vendas.update(listaVenda.get(i));
            }
        }
    }
    
    public void excluirVenda_produto(){
        List <Venda_produto> vendaProduto = new Venda_produtoDao().read();
        Venda_produtoDao vendaProdDao = new Venda_produtoDao();
        Venda_produto vp = new Venda_produto();
        
        int codigoVenda = Integer.parseInt(cod_ultima_venda.getText());
                
        for (int i = 0; i < vendaProduto.size(); i++){
            int codigoVendaBd = vendaProduto.get(i).getCod_vendaFk();
            //int codprod = vendaProduto.get(i).getCod_produtoFk();
            
            if(codigoVenda == codigoVendaBd){
                vp.setCod_vendaFk(codigoVenda);
                vendaProdDao.delete(vp);
            }
        }
    }
    
    public void excluirVenda(){
        List <Venda> vendas = new VendaDao().read();
        VendaDao vendasDao = new VendaDao();
        Venda v = new Venda();
        
        int codigoVenda = Integer.parseInt(cod_ultima_venda.getText());
        
        v.setCod_venda(codigoVenda);
        
        vendasDao.delete(v);
        
    }
    
    public void mostrarVendedorDaVenda(){
        List<Vendedor> VendedorList = new VendedorDao().read();
        VendedorDao vd = new VendedorDao();
         String codigoDoVendedor ;
         List<Login> loginList = new LoginDao().read();
        if(loginList.size() > 0){
           codigoDoVendedor = Integer.toString(loginList.get(loginList.size()-1).getCod_vendedorFk());
            
            //informacao2.setText(codigoDoVendedor);
        
        
        for (int i = 0; i < VendedorList.size(); i++){
            String codigoVendedorBanco = Integer.toString(VendedorList.get(i).getCod_vendedor());
            if(codigoVendedorBanco.equals(codigoDoVendedor)){
                informacao2.setText(VendedorList.get(i).getNome_vendedor());
            }
        }
        }
        
        
    }
    
  
    public void mostrarCodigoDaVenda(){
        
        List<Venda> vendaDao = new VendaDao().read();
       
        if(vendaDao.size() > 0){
            
        String codigoDaVenda = Integer.toString(vendaDao.get(vendaDao.size()-1).getCod_venda());
        cod_ultima_venda.setText(codigoDaVenda);
        
        }  
          
    }
   
    public void carregarPreco(){
    
    List<Produto> listaProdutos = new ProdutoDao().read();
         
    long codigoDigitado = Long.parseLong(codigo_produto_venda.getText());
    
    for(int i = 0; i < listaProdutos.size(); i++){
         
        if(codigoDigitado == listaProdutos.get(i).getCod_produto()){
            preco_produto_venda.setText(Double.toString(listaProdutos.get(i).getPreco_produto()));
        }
    }
    
}
    public void atualizarQuantidadeNoBanco(){
   
    List<Produto> listaProdutos = new ProdutoDao().read();
    ProdutoDao produtoDao = new ProdutoDao();
     
    long codigoDigitado = Long.parseLong(codigo_produto_venda.getText());
    int quantidadeDigitada = Integer.parseInt(quantidade_produto_venda.getText());
    int quantidadeAnteriorNoBd;
    boolean quantidadeIndisponivelNoBd = false;
     
    for(int i = 0; i < listaProdutos.size(); i++){
         
        if(codigoDigitado == listaProdutos.get(i).getCod_produto()){
            
            quantidadeAnteriorNoBd = listaProdutos.get(i).getQuantidade_produto();
            
            quantidadeAnteriorNoBd = quantidadeAnteriorNoBd - quantidadeDigitada;
            listaProdutos.get(i).setQuantidade_produto(quantidadeAnteriorNoBd);
            
            produtoDao.update(listaProdutos.get(i));
            
            if(quantidadeDigitada > listaProdutos.get(i).getQuantidade_produto()){
                quantidadeIndisponivelNoBd = true;
                JOptionPane.showMessageDialog(null, "Quantidade maior que estoque!");
            }
        }
    }
 
}
        

    public double calcularValorTotalDeUmItem(){
        
        double valorTotalDoItem;
        int quantidadeNaVenda;
        double valorUnitario;

        quantidadeNaVenda = Integer.parseInt(quantidade_produto_venda.getText());
        valorUnitario = Double.parseDouble(preco_produto_venda.getText());

        valorTotalDoItem = (quantidadeNaVenda * valorUnitario);

        valor_total_item_venda.setText(Double.toString(valorTotalDoItem));

           return valorTotalDoItem;
    }
    
    public void adicionarProdutosNaCompra(){
        Venda_produto vendaProduto = new Venda_produto();
        
        Venda_produtoDao vendaProdutoDao = new Venda_produtoDao();
                
        vendaProduto.setCod_produtoFk(Long.parseLong(codigo_produto_venda.getText()));
        vendaProduto.setCod_vendaFk(Integer.parseInt(cod_ultima_venda.getText()));
        vendaProduto.setQuantidade_produtos(Integer.parseInt(quantidade_produto_venda.getText()));
      
        vendaProduto.setValor_unitarioproduto(Double.parseDouble(preco_produto_venda.getText()));
       
        vendaProduto.setTotal_venda(Double.parseDouble(valor_total_item_venda.getText()));
        
        
        vendaProdutoDao.create(vendaProduto);
        
    }
    
    public void adicionarProdutosCompradosNaTabela(){
        List<Venda_produto> listaProdutos = new Venda_produtoDao().read();
        //Venda_produtoDao vendaProdutoDao = new Venda_produtoDao();
        String codigoVendaAtual = cod_ultima_venda.getText();
        String codigoProdutoDigitado = codigo_produto_venda.getText();
        
        
        for(int i = 0; i < listaProdutos.size(); i++){
            String codigoVendaNoBd = Integer.toString(listaProdutos.get(i).getCod_vendaFk());
            String codigoProdutoNoBd = Long.toString(listaProdutos.get(i).getCod_produtoFk());
            if((codigoVendaAtual.equals(codigoVendaNoBd)) && (codigoProdutoDigitado.equals(codigoProdutoNoBd))){
         
                DefaultTableModel val = (DefaultTableModel) lista_de_compras.getModel();
                val.addRow(new Object []{listaProdutos.get(i).getCod_produtoFk(),
                        listaProdutos.get(i).getQuantidade_produtos(),
                        listaProdutos.get(i).getValor_unitarioproduto(),    
                        listaProdutos.get(i).getTotal_venda()});
                
            }
                              
                    
        }      
        
    }
    
    
    public void calcularTroco(){
    double valorRecebido = Double.parseDouble(valor_recebido_venda.getText());
    double valorTotalAPagar = Double.parseDouble(total_a_pagar_venda.getText());
    double troco;
        
    troco = (valorRecebido - valorTotalAPagar);
        
    troco_venda1.setText(Double.toString(troco));
        
}
    
    public void carregarNomeDoProdutoVendido(){
        List<Produto> listaProdutos = new ProdutoDao().read();
        
        String codigoDigitado = codigo_produto_venda.getText();
        
        for(int i = 0; i < listaProdutos.size(); i++){
            String codigoProdutoBd = Long.toString(listaProdutos.get(i).getCod_produto());
            if(codigoDigitado.equals(codigoProdutoBd)){
                String nome_produto = listaProdutos.get(i).getNome_produto();
                nome_do_produto_venda.setText(nome_produto);
            }
           
        }
    }
    
    public void mostrarNomeDoProduto(){
        List<Produto> listaProdutos = new ProdutoDao().read();
        
    }
    
    public void limparCampos(){
        cpf_cliente_venda.setText("");
        codigo_produto_venda.setText("");
        quantidade_produto_venda.setText("");
        preco_produto_venda.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_adicionar_cpf_venda;
    private javax.swing.JRadioButton aprazo;
    private javax.swing.JRadioButton avista;
    private javax.swing.JButton cancelar_venda;
    private javax.swing.JLabel cod_ultima_venda;
    private javax.swing.JTextField codigo_produto_venda;
    private javax.swing.JFormattedTextField cpf_cliente_venda;
    private javax.swing.JLabel data_da_venda;
    private javax.swing.JLabel informacao;
    private javax.swing.JLabel informacao2;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_Topo_tela;
    private javax.swing.JPanel jPanel_inf_venda;
    private javax.swing.JPanel jPanel_plano_de_fundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lista_de_compras;
    private javax.swing.JLabel nome_do_produto_venda;
    private javax.swing.JTextField preco_produto_venda;
    private javax.swing.JTextField quantidade_produto_venda;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel total_a_pagar_venda;
    private javax.swing.JLabel troco_venda1;
    private javax.swing.JTextField valor_recebido_venda;
    private javax.swing.JLabel valor_total_item_venda;
    private javax.swing.JButton verPreco;
    // End of variables declaration//GEN-END:variables
}
