/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.xml.bind.DatatypeConverter;
import model.ConnectionFactory;
import model.Produto;
import model.Venda;
import model.Venda_produto;
import model.dao.ProdutoDao;
import model.dao.VendaDao;
import model.dao.Venda_produtoDao;

/**
 *
 * @author jade
 */
public class Vendas extends javax.swing.JFrame {

    /**
     * Creates new form Vendas
     */
    public Vendas() {
        initComponents();
        Venda v = new Venda ();
        
        /*
        Date dat;
        dat = new Date();
        SimpleDateFormat formato;
        formato = new SimpleDateFormat("yyyy-MM-dd");
        data_venda.setText(formato.format(dat));
        
        
        */
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        codigo_produto_venda = new javax.swing.JTextField();
        quantidade_produto_venda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        valor_unitarioproduto_venda = new javax.swing.JTextField();
        jButton_adicionarDetalhesVenda = new javax.swing.JButton();
        cpf_cliente_venda = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        adicionar_produto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        valor_multiplicado_itens = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        valorTotalFinal_compra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        valor_recebido_do_cliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        valor_devolver_paraCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_de_compras = new javax.swing.JTable();
        jButtonFInalizar_compra = new javax.swing.JButton();
        aparecer_na_tela_codigo_venda = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1370, 700));

        jPanel2.setBackground(new java.awt.Color(101, 116, 203));

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF:");

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Produto:");

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Valor:");

        codigo_produto_venda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigo_produto_vendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigo_produto_vendaFocusLost(evt);
            }
        });
        codigo_produto_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_produto_vendaActionPerformed(evt);
            }
        });

        quantidade_produto_venda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantidade_produto_vendaFocusGained(evt);
            }
        });
        quantidade_produto_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidade_produto_vendaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantidade:");

        valor_unitarioproduto_venda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valor_unitarioproduto_vendaFocusGained(evt);
            }
        });

        jButton_adicionarDetalhesVenda.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton_adicionarDetalhesVenda.setText("Adicionar Cpf");
        jButton_adicionarDetalhesVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_adicionarDetalhesVendaActionPerformed(evt);
            }
        });

        try {
            cpf_cliente_venda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data:");

        adicionar_produto.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        adicionar_produto.setText("Adicionar");
        adicionar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionar_produtoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total:");

        valor_multiplicado_itens.setText("0.00");
        valor_multiplicado_itens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_multiplicado_itensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(118, 118, 118))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cpf_cliente_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton_adicionarDetalhesVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(codigo_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valor_multiplicado_itens, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(valor_unitarioproduto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(quantidade_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(adicionar_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf_cliente_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_adicionarDetalhesVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidade_produto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_unitarioproduto_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(valor_multiplicado_itens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(adicionar_produto)
                .addGap(133, 133, 133))
        );

        jPanel3.setBackground(new java.awt.Color(101, 116, 203));

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Valor Recebido:");

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Final:");

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Troco:");

        lista_de_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "quantidade", "Valor", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lista_de_compras);
        if (lista_de_compras.getColumnModel().getColumnCount() > 0) {
            lista_de_compras.getColumnModel().getColumn(0).setHeaderValue("Produto");
            lista_de_compras.getColumnModel().getColumn(1).setHeaderValue("quantidade");
            lista_de_compras.getColumnModel().getColumn(2).setHeaderValue("Valor");
            lista_de_compras.getColumnModel().getColumn(3).setHeaderValue("Total");
        }

        jButtonFInalizar_compra.setText("Finalizar");
        jButtonFInalizar_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFInalizar_compraActionPerformed(evt);
            }
        });

        aparecer_na_tela_codigo_venda.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        aparecer_na_tela_codigo_venda.setForeground(new java.awt.Color(255, 255, 255));
        aparecer_na_tela_codigo_venda.setText("00");

        jLabel13.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Venda:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aparecer_na_tela_codigo_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valor_recebido_do_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(valor_devolver_paraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonFInalizar_compra))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorTotalFinal_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aparecer_na_tela_codigo_venda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorTotalFinal_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_recebido_do_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valor_devolver_paraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFInalizar_compra))))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, 1386, 1386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, 701, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigo_produto_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_produto_vendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_produto_vendaActionPerformed

    private void quantidade_produto_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidade_produto_vendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidade_produto_vendaActionPerformed
   
    private void jButton_adicionarDetalhesVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_adicionarDetalhesVendaActionPerformed
        
        Venda v = new Venda();
        VendaDao vd = new VendaDao();
        List<Venda> lv = new VendaDao().read();
        int lista;
        /*
        Date dat;
        dat = new Date();
        SimpleDateFormat formato;
        formato = new SimpleDateFormat("yyyy-MM-dd");
        data_venda.setText(formato.format(dat));
     */
        v.setCpf_cliente(cpf_cliente_venda.getText());
          
        vd.create(v);
        pegarUltimoCod();
    }//GEN-LAST:event_jButton_adicionarDetalhesVendaActionPerformed
    
    
    private void valor_multiplicado_itensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_multiplicado_itensActionPerformed
        
        
        //efetuar a modificação de preço, caso solicitado pelo usuario
        //cadastrar a data do sistema no banco de dados
        //dividir o método adicionar produto em dois
        //consertar a parte que está mostrando todos os produtos vendidos na tabela de vendas
        
    }//GEN-LAST:event_valor_multiplicado_itensActionPerformed

    
public String RetornarNomeProduto(int codigoDigitado){
    
    List<Produto> produtos = new ProdutoDao().read();
    Produto p = new Produto();
    ProdutoDao pd= new ProdutoDao();
    String nome = null;
    codigoDigitado = Integer.parseInt(codigo_produto_venda.getText());
    boolean achou = false;
     
    for(int i = 0; i < produtos.size(); i++){
        if(codigoDigitado == produtos.get(i).getCod_produto()){
            nome = produtos.get(i).getNome_produto();
        }
  
    }
  
        return nome;
}

public double calculaValorDeItens(){
    double subValor;
    int quantidade;
    double valorUnitario;
     
    quantidade = Integer.parseInt(quantidade_produto_venda.getText());
    valorUnitario = Double.parseDouble(valor_unitarioproduto_venda.getText());
    
    subValor = (quantidade * valorUnitario);
     
    valor_multiplicado_itens.setText(Double.toString(subValor));
     
    return subValor;
     
}
 
 
public void carregaPreco(){
    Produto p = new Produto();
    List<Produto> produtos = new ProdutoDao().read();
    ProdutoDao pd = new ProdutoDao();
     
    int codDigitado = Integer.parseInt(codigo_produto_venda.getText());
    
    for(int i = 0; i < produtos.size(); i++){
         
        if(codDigitado == produtos.get(i).getCod_produto()){
            valor_unitarioproduto_venda.setText(Double.toString(produtos.get(i).getPreco_produto()));
        }
    }
    
}
 
public void subtrairquantidade(){
    Produto p = new Produto();
    List<Produto> produtos = new ProdutoDao().read();
    ProdutoDao pd = new ProdutoDao();
     
    int codDigitado = Integer.parseInt(codigo_produto_venda.getText());
    int quantidadeDig = Integer.parseInt(quantidade_produto_venda.getText());
    int quantBd;
    boolean maior = false;
     
    for(int i = 0; i < produtos.size(); i++){
         
        if(codDigitado == produtos.get(i).getCod_produto()){
            quantBd = produtos.get(i).getQuantidade_produto();
            quantBd = quantBd - quantidadeDig;
            produtos.get(i).setQuantidade_produto(quantBd);
            pd.update(produtos.get(i));
            
            if(quantidadeDig > produtos.get(i).getQuantidade_produto()){
                maior = true;
                JOptionPane.showMessageDialog(null, "Quantidade maior que estoque!");
            }
        }
    }
 
}
 
public void calcularTroco(){
    double valorRecebido = Double.parseDouble(valor_recebido_do_cliente.getText());
    double valorTotalCompra = Double.parseDouble(valorTotalFinal_compra.getText());
    double troco ;
        
    troco = (valorRecebido - valorTotalCompra);
        
    valor_devolver_paraCliente.setText(Double.toString(troco));
        
}

public void pegarUltimoCod(){
    Venda v = new Venda();
    List<Venda> vd = new VendaDao().read();
    boolean achou = false;
    
    if(vd.size() > 0){
       String i = Integer.toString(vd.get(vd.size()-1).getCod_venda());
       aparecer_na_tela_codigo_venda.setText(i);
    }  
          
}


 
public void adicionarProdutos(){
    Venda_produto vp = new Venda_produto();
    Venda_produtoDao vpd = new Venda_produtoDao();
    List<Venda_produto> vpl = new Venda_produtoDao().read();
    Venda v = new Venda();
    //ArrayList<Venda_produto> vpl = new ArrayList<>();
    double valorFinal = 0;
    double varAuxiliar = 0;
    
    
    //do{ 
    vp.setCod_produtoFk(Integer.parseInt(codigo_produto_venda.getText()));
    vp.setCod_vendaFk(Integer.parseInt(aparecer_na_tela_codigo_venda.getText()));
    vp.setQuantidade_produtos(Integer.parseInt(quantidade_produto_venda.getText()));
    
    subtrairquantidade();
        
    vp.setValor_unitarioproduto(Double.parseDouble(valor_unitarioproduto_venda.getText()));
    
    vp.setTotal_venda(Double.parseDouble(valor_multiplicado_itens.getText())); 
    vpd.create(vp);
    vpl.add(vp);
    //JOptionPane.showInputDialog("continuar?", op);
    //}while(op == 1);
    int codV = Integer.parseInt(aparecer_na_tela_codigo_venda.getText());
     
    for(int i =0 ; i < vpl.size(); i++){
        int k = 0;
        
        //if(vpl.get(i).getCod_vendaFk() == codV){
            lista_de_compras.setValueAt(vpl.get(i).getCod_produtoFk(), i, k);
            lista_de_compras.setValueAt(vpl.get(i).getQuantidade_produtos(), i, k+1);
            lista_de_compras.setValueAt(vpl.get(i).getValor_unitarioproduto(), i, k+2);
            lista_de_compras.setValueAt(vpl.get(i).getTotal_venda(), i, k+3);
        
         //} 
       
        
        
        double subtotal = vpl.get(i).getTotal_venda();
        valorFinal = (varAuxiliar + subtotal);
        varAuxiliar = valorFinal;
         k++;
        
                  
    }
        
        valorTotalFinal_compra.setText(Double.toString(varAuxiliar)); 
    
    
    limparCampos();
       
}
 
public void limparTabela(){
     List<Venda_produto> vpl = new Venda_produtoDao().read();
     for (int i = 0; i < vpl.size(); i++){
          
        
     }
    
}
    private void adicionar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionar_produtoActionPerformed
         
        adicionarProdutos();
 
    }//GEN-LAST:event_adicionar_produtoActionPerformed
    
        

    
    private void jButtonFInalizar_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFInalizar_compraActionPerformed
       Venda v = new Venda();
       VendaDao vd = new VendaDao();
       List<Venda> vendas = new VendaDao().read();
       int codVendaDig = Integer.parseInt(aparecer_na_tela_codigo_venda.getText());
       boolean achou = false;
       calcularTroco();
       
       for(int i = 0; i < vendas.size(); i++){
           if(codVendaDig == vendas.get(i).getCod_venda()){
              
               vendas.get(i).setValorTotal_venda(Double.parseDouble(valorTotalFinal_compra.getText()));
               vendas.get(i).setValorPago_pelo_cliente(Double.parseDouble(valor_recebido_do_cliente.getText()));
               
               vd.update(vendas.get(i));
               
           }
           
       }
       
        JOptionPane.showMessageDialog(null, "Venda Encerrada ");

        limparTudo();
        limparTabela();
        
    }//GEN-LAST:event_jButtonFInalizar_compraActionPerformed

    private void quantidade_produto_vendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantidade_produto_vendaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidade_produto_vendaFocusGained

    private void valor_unitarioproduto_vendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valor_unitarioproduto_vendaFocusGained
        // TODO add your handling code here:
        calculaValorDeItens();
    }//GEN-LAST:event_valor_unitarioproduto_vendaFocusGained

    private void codigo_produto_vendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigo_produto_vendaFocusGained
        // TODO add your handling code here:
         
    }//GEN-LAST:event_codigo_produto_vendaFocusGained

    private void codigo_produto_vendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigo_produto_vendaFocusLost
        // TODO add your handling code here:
        carregaPreco();
    }//GEN-LAST:event_codigo_produto_vendaFocusLost
    
    public void limparCampos(){
        
        codigo_produto_venda.setText("");
        quantidade_produto_venda.setText("");
        valor_unitarioproduto_venda.setText("");
        
    }
    public void limparTudo(){
        
            //double calc = 0; 
            //calc = calculaValorDeItens();
            //lista_de_compras.
            cpf_cliente_venda.setText("");
            valorTotalFinal_compra.setText("");
            valor_recebido_do_cliente.setText("");
            valor_devolver_paraCliente.setText("");
            aparecer_na_tela_codigo_venda.setText("");
            valor_multiplicado_itens.setText("");
           
        
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
                
              
            }
        });
        
        
        //consertar erro de aparecer produtos que não são da compra;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar_produto;
    private javax.swing.JLabel aparecer_na_tela_codigo_venda;
    private javax.swing.JTextField codigo_produto_venda;
    private javax.swing.JFormattedTextField cpf_cliente_venda;
    private javax.swing.JButton jButtonFInalizar_compra;
    private javax.swing.JButton jButton_adicionarDetalhesVenda;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lista_de_compras;
    private javax.swing.JTextField quantidade_produto_venda;
    private javax.swing.JTextField valorTotalFinal_compra;
    private javax.swing.JTextField valor_devolver_paraCliente;
    private javax.swing.JTextField valor_multiplicado_itens;
    private javax.swing.JTextField valor_recebido_do_cliente;
    private javax.swing.JTextField valor_unitarioproduto_venda;
    // End of variables declaration//GEN-END:variables
}
